site_name: EDIA
site-url: https://edia-toolbox.github.io/

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - md_in_html
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

theme: 
  logo: assets/logo.png
  favicon: assets/favicon.ico
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    
  name: material
  palette: 
    # Light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

    # Dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue
      accent: deep orange
  extra_css:
    - css/custom.css
  
nav:
  - Home: index.md
  - Getting Started: gettingstarted.md
  - API Reference:
      - API Reference: apiref.md
  - Contact us: contact.md
